import type { Metadata } from "next";
import "./globals.css";
import { Tinos } from "next/font/google";
import { VisualEditing } from "next-sanity/visual-editing";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { draftMode } from "next/headers";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Stolpersteine",
  description: "Generated by create next app",
};

const tinos = Tinos({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tinos.className}>
        {children}
        <SanityLive />
        {(await draftMode()).isEnabled && (
          <>
            <VisualEditing />
            <DisableDraftMode />
          </>
        )}
      </body>
    </html>
  );
}
